-module(client).
-compile(export_all).


gen_coin(Value, Leading_Zeroes) ->
    AllowedChars = "qwertyuiopasdfghjklzxcvbnm[]\';./,{}|:<>?",

    Ranstring = lists:foldl(fun(_, Acc) ->
                    [lists:nth(rand:uniform(length(AllowedChars)),
                                AllowedChars)]
                              ++ Acc
                    end, [] , lists:seq(1, 10)),

    UFID = "devangkale",
    Finalstring = string:concat(UFID, Ranstring),
    FinalSHA256 = io_lib:format("~64.16.0b", [binary:decode_unsigned(crypto:hash(sha256, Finalstring))]),
    Check_Zeroes = string:slice(FinalSHA256, 0, Value),
    Status = string:equal(Check_Zeroes,Leading_Zeroes),
    if 
        Status -> 
            NodeName = node(),
            io:fwrite("The required coin generated by: ~s  is: ~p  with SHA256 Hash: ~p~n", [NodeName, Finalstring, FinalSHA256]),
            {_, Time1} = statistics(runtime), 
            {_, Time2} = statistics(wall_clock),
            U1 = Time1,
            U2 = Time2,
            U3 = "undef",
            try U1/U2 of 
                 _ -> {ok, Fd} = file:open("Result_Remote.txt",[append]),
                 io:format(Fd, "The required coin generated by: ~s  is ~p   with SHA256 Hash:  ~p.~n  METRICS:: [PID: ~p CPU Time : ~p, Real Time: ~p, Ratio[CPU_TIME/REAL_TIME] = ~p]~n", [NodeName, Finalstring,FinalSHA256,self(),U1, U2, U1/U2])
            catch 
                error:badarith -> {ok, Fd} = file:open("Result_Remote.txt",[append]),
                io:format(Fd, "The required coin generated by: ~s  is ~p  ~p.~n  METRICS:: [PID: ~p CPU Time : ~p, Real Time: ~p, Ratio[CPU_TIME/REAL_TIME] = ~p]~n", [NodeName, Finalstring,FinalSHA256,self(),U1, U2, U3])
            end;
        true ->
                % io:fwrite("Coin Not Found ~n")
            []
    end.

main(0, _, _) ->
    io:fwrite("Closing the worker with PID::~w~n",[self()]),
    exit(self());
    
main(Workload_Dist, KValue, Leading_Zeroes) ->
    % io:fwrite("Searching coin on ~w~n", [self()]),
    gen_coin(KValue, Leading_Zeroes),
    main(Workload_Dist-1, KValue, Leading_Zeroes).

% for_run(0,_,_,_) ->  
%         io:fwrite("All remote workers are spawned now:: Bye!!~n");

% for_run(Worker,KValue,Leading_Zeroes, Workload) when Worker > 0 -> 
%     % Pid = spawn(client, main, [Workload, KValue, Leading_Zeroes]), 
%     io:fwrite("Remote Worker generated with the PID  ~w~n", [Pid]),
%     for_run(Worker-1,KValue,Leading_Zeroes, Workload).

run() ->
    receive
        {Client, {KValue, Workload_Dist, generate_bitcoin}} ->

            Leading_Zeroes = lists:concat(lists:duplicate(KValue, "0")),
            file:delete("Result_Remote.txt"),
            Pid_Remote = spawn(client, main, [Workload_Dist, KValue, Leading_Zeroes])
            % for_run(8,KValue,Leading_Zeroes, Workload_Dist)
end.